name: dev-apply

on:
  push:
    branches:
      - main
env:
  # please set your own app name corresponding with application name.
  # APP_NAME: ${{ github.event.repository.name }}
  APP_NAME: housebokan

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo Setup

  terraform-prod:
    name: Terraform-Prod
    runs-on: ubuntu-latest
    needs: Setup

    defaults:
      run:
        shell: bash
        working-directory: "./src/prod"
    steps:
      - name: Create .env file
      - shell: bash
        run: |
          touch .env
          echo "TF_VAR_DB_NAME=${{ secrets.PROD_TF_VAR_DB_NAME }}" >> .env
          echo "TF_VAR_DB_MASTER_NAME=${{ secrets.PROD_TF_VAR_DB_MASTER_NAME }}" >> .env
          echo "TF_VAR_DB_MASTER_PASS=${{ secrets.PROD_TF_VAR_DB_MASTER_PASS }}" >> .env
          echo "TF_VAR_APP_KEY=${{ secrets.PROD_TF_VAR_APP_KEY }}" >> .env

      - name: Checkout
        uses: actions/checkout@v2

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.3

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
